### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by julien-c** [tarekziade/boom#67]
```
Traceback (most recent call last):
  File "/usr/local/bin/boom", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/boom/boom.py", line 418, in main
    post_hook=args.post_hook, quiet=(args.json_output or args.quiet))
  File "/usr/local/lib/python3.6/site-packages/boom/boom.py", line 286, in load
    print_server_info(url, method, headers=headers)
  File "/usr/local/lib/python3.6/site-packages/boom/boom.py", line 136, in print_server_info
    res = requests.head(url)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 98, in head
    return request('head', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 265, in create_urllib3_context
    context.options |= options
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 322 more times]
RecursionError: maximum recursion depth exceeded

```

**Comment by tspicer** [comment]
Confirmed, the same issue using Alpine Linux

**Comment by tspicer** [comment]
I downgraded to Python 3.5.3 and all was fine

**Comment by tarekziade** [comment]
closing, see #64
