### ISSUE TITLE
from boom.boom import load gets ModuleNotFoundError

### ISSUE THREAD

**Issue by GaMagenFOX** [tarekziade/boom#77]
Hi, dear tarekziade,

this is a very useful module for testing and thanks for your amazing work!
after I install it with pip and following the doc do the same way then I get ModuleNotFoundError

code:  

> 
> from boom.boom import load
> result = load('http://example.com/', 1, 1, 0, 'GET', None, 'text/plain', None, quiet=True)
> 
> 

error info:

> 
> D:\ProgramData\Anaconda3\envs\py3.8_boom\python.exe E:/Python/worktools/BoomTest/boom.py
> Traceback (most recent call last):
>   File "E:/Python/worktools/BoomTest/boom.py", line 1, in <module>
>     from boom.boom import load
>   File "E:\Python\worktools\BoomTest\boom.py", line 1, in <module>
>     from boom.boom import load
> ModuleNotFoundError: No module named 'boom.boom'; 'boom' is not a package
> 
> Process finished with exit code 1
> 

is it the namespace problem? or I'm doing something wrong

hope you can help

**Comment by GaMagenFOX** [comment]
copy the project file instead of pip install it can fix it
thanks
